import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import type { WSState } from "@/hooks/useWebSocket";
import { Play, Square, RotateCcw, Sun, Moon, LogOut, Volume2, VolumeX } from "lucide-react";
import { API_URL } from "@/lib/config";
import { ShareButton } from "./ShareButton";

type StatusBarProps = {
  loopStatus: "stopped" | "running" | "waiting" | "unknown";
  iterationCount: number;
  loopStartTime: number | null;
  wsState: WSState;
  sessionId?: string;
  onError?: (message: string) => void;
  /** Number of tasks generated by Ralphy. */
  taskCount?: number;
  /** Current theme, used to show correct icon. */
  theme?: "dark" | "light";
  /** Called to toggle the global theme. */
  onThemeToggle?: () => void;
  /** Called to log out and return to WelcomePage. */
  onLogout?: () => void;
  /** Whether sound notifications are on. */
  soundEnabled?: boolean;
  /** Called to toggle sound notifications. */
  onSoundToggle?: () => void;
};

// Terminal-specific status dot colors -- intentionally not theme-switched.
const STATUS_CONFIG = {
  running: { color: "bg-[#00FF41] animate-pulse-dot", label: "RUNNING" },
  waiting: { color: "bg-[#FFaa00]", label: "WAITING" },
  stopped: { color: "bg-[#FF0033]", label: "STOPPED" },
  unknown: { color: "bg-muted-foreground", label: "UNKNOWN" },
} as const;

function formatUptime(seconds: number): string {
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = Math.floor(seconds % 60);
  if (h > 0) return `${h}h ${m}m ${s}s`;
  if (m > 0) return `${m}m ${s}s`;
  return `${s}s`;
}

/** Pad iteration count to 3 digits. */
function fmtIter(n: number): string {
  return String(n).padStart(3, "0");
}

async function loopAction(
  action: "start" | "stop" | "restart",
  sessionId?: string,
  onError?: (msg: string) => void,
) {
  if (!sessionId) return;
  const base = `${API_URL}/api/sessions/${sessionId}`;
  try {
    const resp = await fetch(`${base}/${action}`, { method: "POST" });
    if (!resp.ok) onError?.("Action failed");
  } catch {
    onError?.("Action failed");
  }
}

export function StatusBar({
  loopStatus,
  iterationCount,
  loopStartTime,
  wsState,
  sessionId,
  onError,
  taskCount = 0,
  theme,
  onThemeToggle,
  onLogout,
  soundEnabled,
  onSoundToggle,
}: StatusBarProps) {
  const [uptime, setUptime] = useState(0);

  useEffect(() => {
    if (!loopStartTime || loopStatus !== "running") {
      setUptime(0);
      return;
    }
    setUptime(Math.floor(Date.now() / 1000 - loopStartTime));
    const interval = setInterval(() => {
      setUptime(Math.floor(Date.now() / 1000 - loopStartTime));
    }, 1000);
    return () => clearInterval(interval);
  }, [loopStartTime, loopStatus]);

  const status = STATUS_CONFIG[loopStatus];
  const wsConnected = wsState === "connected";

  return (
    <div className="flex items-center justify-between px-4 py-2 border-b border-border bg-card font-mono text-xs uppercase tracking-wider">
      {/* Left: loop status */}
      <div className="flex items-center gap-2">
        <span className={`w-2 h-2 ${status.color}`} />
        <span className="text-foreground">{status.label}</span>
      </div>

      {/* Center: iteration + uptime + task count badge */}
      <div className="flex items-center gap-3">
        <span>
          <span className="text-muted-foreground">ITER:</span>
          <span className="text-foreground">#{fmtIter(iterationCount)}</span>
        </span>
        {loopStatus === "running" && loopStartTime && (
          <>
            <span className="text-muted-foreground">|</span>
            <span className="text-primary">{formatUptime(uptime)}</span>
          </>
        )}
        <span className="text-muted-foreground">|</span>
        <span className="flex items-center gap-1">
          <span className="text-muted-foreground">TASKS:</span>
          <span
            className={`inline-flex items-center justify-center min-w-[1.25rem] h-5 px-1.5 text-[10px] font-mono font-semibold rounded-full transition-colors ${
              taskCount > 0
                ? "bg-primary text-primary-foreground"
                : "border border-border text-muted-foreground"
            }`}
          >
            {taskCount}
          </span>
        </span>
      </div>

      {/* Right: ws status + theme toggle + controls */}
      <div className="flex items-center gap-3">
        {wsConnected ? (
          <span className="text-primary">WS:OK</span>
        ) : (
          <span className="text-destructive">WS:OFF</span>
        )}

        <span className="text-muted-foreground">|</span>

        {/* Sound toggle */}
        {onSoundToggle && (
          <button
            onClick={onSoundToggle}
            aria-label={soundEnabled ? "Disable sound notifications" : "Enable sound notifications"}
            title={soundEnabled ? "Sound: ON" : "Sound: OFF"}
            className="p-1 border border-border hover:border-primary text-foreground hover:text-primary transition-colors"
          >
            {soundEnabled ? <Volume2 className="size-3" /> : <VolumeX className="size-3" />}
          </button>
        )}

        {/* Theme toggle */}
        {onThemeToggle && (
          <button
            onClick={onThemeToggle}
            aria-label={theme === "dark" ? "Switch to light mode" : "Switch to dark mode"}
            title={theme === "dark" ? "Switch to light mode" : "Switch to dark mode"}
            className="p-1 border border-border hover:border-primary text-foreground hover:text-primary transition-colors"
          >
            {theme === "dark" ? <Sun className="size-3" /> : <Moon className="size-3" />}
          </button>
        )}

        <span className="text-muted-foreground">|</span>

        {/* Loop controls */}
        <div className="flex items-center gap-1">
          <button
            onClick={() => loopAction("start", sessionId, onError)}
            title="Start loop"
            className="p-1 border border-border hover:border-primary text-foreground hover:text-primary transition-colors"
          >
            <Play className="size-3" />
          </button>
          <button
            onClick={() => loopAction("stop", sessionId, onError)}
            title="Stop loop"
            className="p-1 border border-border hover:border-primary text-foreground hover:text-primary transition-colors"
          >
            <Square className="size-3" />
          </button>
          <button
            onClick={() => loopAction("restart", sessionId, onError)}
            title="Restart loop"
            className="p-1 border border-border hover:border-primary text-foreground hover:text-primary transition-colors"
          >
            <RotateCcw className="size-3" />
          </button>
        </div>

        {/* Share button: only shown when a session is active */}
        {sessionId && (
          <>
            <span className="text-muted-foreground">|</span>
            <ShareButton sessionId={sessionId} onError={onError} />
          </>
        )}

        {onLogout && (
          <>
            <span className="text-muted-foreground">|</span>
            <button
              onClick={onLogout}
              title="Log out"
              aria-label="Log out"
              className="p-1 border border-border hover:border-destructive text-muted-foreground hover:text-destructive transition-colors"
            >
              <LogOut className="size-3" />
            </button>
          </>
        )}
      </div>
    </div>
  );
}
