import { useEffect, useState, useCallback } from "react";
import * as AlertDialog from "@radix-ui/react-alert-dialog";
import type { WSState } from "@/hooks/useWebSocket";
import { Play, Square, RotateCcw, Sun, Moon, LogOut, Volume2, VolumeX, Skull } from "lucide-react";
import { API_URL } from "@/lib/config";
import { ShareButton } from "./ShareButton";

type StatusBarProps = {
  loopStatus: "stopped" | "running" | "waiting" | "unknown";
  iterationCount: number;
  loopStartTime: number | null;
  wsState: WSState;
  sessionId?: string;
  onError?: (message: string) => void;
  /** Number of tasks generated by Ralphy. */
  taskCount?: number;
  /** Current theme, used to show correct icon. */
  theme?: "dark" | "light";
  /** Called to toggle the global theme. */
  onThemeToggle?: () => void;
  /** Called to log out and return to WelcomePage. */
  onLogout?: () => void;
  /** Whether sound notifications are on. */
  soundEnabled?: boolean;
  /** Called to toggle sound notifications. */
  onSoundToggle?: () => void;
};

// Status dot colors using semantic design tokens.
const STATUS_CONFIG = {
  running: { color: "bg-[var(--color-success)] animate-pulse-dot", label: "RUNNING" },
  waiting: { color: "bg-[var(--color-warning)]", label: "WAITING" },
  stopped: { color: "bg-[var(--color-error)]", label: "STOPPED" },
  unknown: { color: "bg-muted-foreground", label: "UNKNOWN" },
} as const;

function formatUptime(seconds: number): string {
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = Math.floor(seconds % 60);
  if (h > 0) return `${h}h ${m}m ${s}s`;
  if (m > 0) return `${m}m ${s}s`;
  return `${s}s`;
}

/** Pad iteration count to 3 digits. */
function fmtIter(n: number): string {
  return String(n).padStart(3, "0");
}

async function loopAction(
  action: "start" | "stop" | "restart" | "kill-task",
  sessionId?: string,
  onError?: (msg: string) => void,
  opts?: { force?: boolean },
) {
  if (!sessionId) return;
  const base = `${API_URL}/api/sessions/${sessionId}`;
  const url = opts?.force ? `${base}/${action}?force=true` : `${base}/${action}`;
  try {
    const resp = await fetch(url, { method: "POST" });
    if (!resp.ok) {
      const body = await resp.json().catch(() => null);
      const detail = body?.detail;
      if (detail && typeof detail === "object") {
        onError?.(`${detail.error}. ${detail.suggestion ?? ""}`);
      } else if (typeof detail === "string") {
        onError?.(detail);
      } else {
        onError?.(`${action} failed (${resp.status})`);
      }
    }
  } catch {
    onError?.(`${action} request failed -- network error`);
  }
}

export function StatusBar({
  loopStatus,
  iterationCount,
  loopStartTime,
  wsState,
  sessionId,
  onError,
  taskCount = 0,
  theme,
  onThemeToggle,
  onLogout,
  soundEnabled,
  onSoundToggle,
}: StatusBarProps) {
  const [uptime, setUptime] = useState(0);

  useEffect(() => {
    if (!loopStartTime || loopStatus !== "running") {
      setUptime(0);
      return;
    }
    setUptime(Math.floor(Date.now() / 1000 - loopStartTime));
    const interval = setInterval(() => {
      setUptime(Math.floor(Date.now() / 1000 - loopStartTime));
    }, 1000);
    return () => clearInterval(interval);
  }, [loopStartTime, loopStatus]);

  const status = STATUS_CONFIG[loopStatus];
  const wsConnected = wsState === "connected";

  return (
    <div className="flex items-center justify-between px-4 py-2 border-b border-border bg-card font-mono text-xs uppercase tracking-wider">
      {/* Left: loop status */}
      <div className="flex items-center gap-2">
        <span className={`w-2 h-2 ${status.color}`} />
        <span className="text-foreground">{status.label}</span>
      </div>

      {/* Center: iteration + uptime + task count badge */}
      <div className="flex items-center gap-3">
        <span>
          <span className="text-muted-foreground">ITER:</span>
          <span className="text-foreground">#{fmtIter(iterationCount)}</span>
        </span>
        {loopStatus === "running" && loopStartTime && (
          <>
            <span className="text-muted-foreground">|</span>
            <span className="text-primary">{formatUptime(uptime)}</span>
          </>
        )}
        <span className="text-muted-foreground">|</span>
        <span className="flex items-center gap-1">
          <span className="text-muted-foreground">TASKS:</span>
          <span
            className={`inline-flex items-center justify-center min-w-[1.25rem] h-5 px-1.5 text-[10px] font-mono font-semibold rounded-full transition-colors ${
              taskCount > 0
                ? "bg-primary text-primary-foreground"
                : "border border-border text-muted-foreground"
            }`}
          >
            {taskCount}
          </span>
        </span>
      </div>

      {/* Right: ws status + theme toggle + controls */}
      <div className="flex items-center gap-3">
        {wsConnected ? (
          <span className="text-primary">WS:OK</span>
        ) : (
          <span className="text-destructive">WS:OFF</span>
        )}

        <span className="text-muted-foreground">|</span>

        {/* Sound toggle */}
        {onSoundToggle && (
          <button
            onClick={onSoundToggle}
            aria-label={soundEnabled ? "Disable sound notifications" : "Enable sound notifications"}
            title={soundEnabled ? "Sound: ON" : "Sound: OFF"}
            className="p-1 border border-border hover:border-primary text-foreground hover:text-primary transition-colors"
          >
            {soundEnabled ? <Volume2 className="size-3" /> : <VolumeX className="size-3" />}
          </button>
        )}

        {/* Theme toggle */}
        {onThemeToggle && (
          <button
            onClick={onThemeToggle}
            aria-label={theme === "dark" ? "Switch to light mode" : "Switch to dark mode"}
            title={theme === "dark" ? "Switch to light mode" : "Switch to dark mode"}
            className="p-1 border border-border hover:border-primary text-foreground hover:text-primary transition-colors"
          >
            {theme === "dark" ? <Sun className="size-3" /> : <Moon className="size-3" />}
          </button>
        )}

        <span className="text-muted-foreground">|</span>

        {/* Loop controls with confirmation dialogs */}
        <LoopControls
          sessionId={sessionId}
          loopStatus={loopStatus}
          onError={onError}
        />

        {/* Share button: only shown when a session is active */}
        {sessionId && (
          <>
            <span className="text-muted-foreground">|</span>
            <ShareButton sessionId={sessionId} onError={onError} />
          </>
        )}

        {onLogout && (
          <>
            <span className="text-muted-foreground">|</span>
            <button
              onClick={onLogout}
              title="Log out"
              aria-label="Log out"
              className="p-1 border border-border hover:border-destructive text-muted-foreground hover:text-destructive transition-colors"
            >
              <LogOut className="size-3" />
            </button>
          </>
        )}
      </div>
    </div>
  );
}

// -- Confirmation dialog + loop control buttons --------------------------------

function ConfirmDialog({
  open,
  onOpenChange,
  title,
  description,
  confirmLabel,
  onConfirm,
}: {
  open: boolean;
  onOpenChange: (v: boolean) => void;
  title: string;
  description: string;
  confirmLabel: string;
  onConfirm: () => void;
}) {
  return (
    <AlertDialog.Root open={open} onOpenChange={onOpenChange}>
      <AlertDialog.Portal>
        <AlertDialog.Overlay className="fixed inset-0 z-50 bg-black/70 backdrop-blur-sm" />
        <AlertDialog.Content className="fixed z-50 top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[380px] bg-card border border-border p-5 font-mono shadow-2xl">
          <AlertDialog.Title className="text-foreground text-xs uppercase tracking-widest mb-2">
            {title}
          </AlertDialog.Title>
          <AlertDialog.Description className="text-muted-foreground text-xs mb-4">
            {description}
          </AlertDialog.Description>
          <div className="flex items-center gap-2 justify-end">
            <AlertDialog.Cancel asChild>
              <button className="px-3 py-1.5 border border-border text-muted-foreground hover:text-foreground text-xs uppercase tracking-wider transition-colors">
                Cancel
              </button>
            </AlertDialog.Cancel>
            <AlertDialog.Action asChild>
              <button
                onClick={onConfirm}
                className="px-3 py-1.5 border border-red-500 text-red-400 hover:bg-red-500 hover:text-black text-xs uppercase tracking-wider transition-colors"
              >
                {confirmLabel}
              </button>
            </AlertDialog.Action>
          </div>
        </AlertDialog.Content>
      </AlertDialog.Portal>
    </AlertDialog.Root>
  );
}

function LoopControls({
  sessionId,
  loopStatus,
  onError,
}: {
  sessionId?: string;
  loopStatus: string;
  onError?: (msg: string) => void;
}) {
  const [confirmAction, setConfirmAction] = useState<"stop" | "restart" | "force_stop" | "kill_task" | null>(null);

  const execute = useCallback(async () => {
    if (!confirmAction) return;
    switch (confirmAction) {
      case "stop":
        await loopAction("stop", sessionId, onError);
        break;
      case "restart":
        await loopAction("restart", sessionId, onError);
        break;
      case "force_stop":
        await loopAction("stop", sessionId, onError, { force: true });
        break;
      case "kill_task":
        await loopAction("kill-task", sessionId, onError);
        break;
    }
    setConfirmAction(null);
  }, [confirmAction, sessionId, onError]);

  const confirmMessages: Record<string, { title: string; desc: string; label: string }> = {
    stop: {
      title: "Stop Loop",
      desc: "The current task will be marked BLOCKED. The loop will not process further tasks until restarted.",
      label: "Stop",
    },
    restart: {
      title: "Restart Loop",
      desc: "The current iteration will complete, then the loop restarts from the next ready task.",
      label: "Restart",
    },
    force_stop: {
      title: "Force Stop",
      desc: "This will kill the agent subprocess immediately. The current task will be marked BLOCKED. Use only if the loop is unresponsive.",
      label: "Force Stop",
    },
    kill_task: {
      title: "Kill Current Task",
      desc: "The current agent subprocess will be killed and the task marked BLOCKED. The loop continues to the next task.",
      label: "Kill Task",
    },
  };

  const active = confirmAction ? confirmMessages[confirmAction] : null;

  return (
    <>
      <div className="flex items-center gap-1">
        <button
          onClick={() => loopAction("start", sessionId, onError)}
          title={`Start loop (status: ${loopStatus})`}
          className="p-1 border border-border hover:border-primary text-foreground hover:text-primary transition-colors"
        >
          <Play className="size-3" />
        </button>
        <button
          onClick={() => setConfirmAction("stop")}
          title={`Stop loop (status: ${loopStatus})`}
          className="p-1 border border-border hover:border-primary text-foreground hover:text-primary transition-colors"
        >
          <Square className="size-3" />
        </button>
        <button
          onClick={() => setConfirmAction("restart")}
          title={`Restart loop (status: ${loopStatus})`}
          className="p-1 border border-border hover:border-primary text-foreground hover:text-primary transition-colors"
        >
          <RotateCcw className="size-3" />
        </button>
        <button
          onClick={() => setConfirmAction("kill_task")}
          title={`Kill current task (status: ${loopStatus})`}
          className="p-1 border border-border hover:border-red-500 text-foreground hover:text-red-400 transition-colors"
        >
          <Skull className="size-3" />
        </button>
      </div>

      {active && (
        <ConfirmDialog
          open={!!confirmAction}
          onOpenChange={(v) => { if (!v) setConfirmAction(null); }}
          title={active.title}
          description={active.desc}
          confirmLabel={active.label}
          onConfirm={execute}
        />
      )}
    </>
  );
}
